### ISSUE TITLE
ONYX.WEATHER ?

### ISSUE THREAD

**Issue by mrogin-technic** [muhlba91/onyx-homeassistant-integration#72] opened 2023-11-15 08:26 UTC
Unfortunately, my ONYX.WEATHER is not integrated to Home Assistant. Is ONYX.WEATHER not yet integrated and if so, when can it be expected, because I need the ONYX.WEATHER in Home Assistant.

**Comment by muhlba91** [comment] 2023-11-15 11:05
first off, i do not own an ONYX.WEATHER device myself, and i am also unable to test such an entity and integration.
this is why i was and am reluctant to support it, as i can never confirm if it is working correctly.

i implemented this sensor according to the API specification in the client itself, though (https://github.com/muhlba91/onyx-client/blob/main/onyx_client/device/weather.py), based on https://github.com/hella-info/onyx_api?tab=readme-ov-file#weather-stations.

what would still be necessary is mapping that entity to sensor entities in home assistant.
as far as i can tell, using a weather entity is impossible - a weather entity requires a condition that the sensor doesn't provide. a weather entity also does not support the brightness measurements that the sensor provides.
hence, the only solution i see is to create multiple sensor entities that map the ONYX.WEATHER sensor values to home assistant sensors.

i'm open to implementing basic support for these sensors, though with the caveat that they will be/stay untested from my side.
let me know what you think, especially if the plan to add multiple standalone sensors would work for your use case and if the data received by the sensor is still the same as mentioned in the API specification (https://github.com/hella-info/onyx_api?tab=readme-ov-file#weather-stations). i'd then add support in the next few weeks, as described above.

**Comment by Jibberchris** [comment] 2023-11-15 11:25
An integration of the weather station would be great. I thought that it hadn't been integrated yet due to a lack of testing opportunities. I would be delighted and would create individual sensors in Homassistant. Many thanks at this point for the very successful ONYX integration.

**Comment by mrogin-technic** [comment] 2023-11-15 11:37
> first off, i do not own an ONYX.WEATHER device myself, and i am also unable to test such an entity and integration. this is why i was and am reluctant to support it, as i can never confirm if it is working correctly.
> 
> i implemented this sensor according to the API specification in the client itself, though (https://github.com/muhlba91/onyx-client/blob/main/onyx_client/device/weather.py), based on https://github.com/hella-info/onyx_api?tab=readme-ov-file#weather-stations.
> 
> what would still be necessary is mapping that entity to sensor entities in home assistant. as far as i can tell, using a weather entity is impossible - a weather entity requires a condition that the sensor doesn't provide. a weather entity also does not support the brightness measurements that the sensor provides. hence, the only solution i see is to create multiple sensor entities that map the ONYX.WEATHER sensor values to home assistant sensors.
> 
> i'm open to implementing basic support for these sensors, though with the caveat that they will be/stay untested from my side. let me know what you think, especially if the plan to add multiple standalone sensors would work for your use case and if the data received by the sensor is still the same as mentioned in the API specification (https://github.com/hella-info/onyx_api?tab=readme-ov-file#weather-stations). i'd then add support in the next few weeks, as described above.

Thank you very much for the quick reply.
Why I would have liked to have the ONYX.WEATHER in HA is as follows:
- The ONYX app from Hella only shows the current values. But since I live in an area with a strong foehn storm, I am looking for a way to see the history of wind, sun, temperature, humidity and air pressure from the last hours, days or weeks and I was recommended to do it via HA if there is a ONYX integration. So I bought a Rapi and set up HA and this integration and now realized that there is no ONYX.WEATHER data available.

**Comment by mrogin-technic** [comment] 2023-11-15 11:42
If i use api.hella.link/box/.../api/v3/devices/... I  just received the following response:
`{
	"name": "Wettersensor",
	"type": "weather",
	"actions": [
		"wink"
	],
	"properties": {
		"air_pressure": {
			"type": "numeric",
			"minimum": 0,
			"maximum": 150000,
			"value": 90374,
			"readonly": true
		},
		"humidity": {
			"type": "numeric",
			"minimum": 0,
			"maximum": 100,
			"value": 78,
			"readonly": true
		},
		"sun_brightness_peak": {
			"type": "numeric",
			"minimum": 0,
			"maximum": 150000,
			"value": 53710,
			"readonly": true
		},
		"sun_brightness_sink": {
			"type": "numeric",
			"minimum": 0,
			"maximum": 150001,
			"value": 20966,
			"readonly": true
		},
		"temperature": {
			"type": "numeric",
			"minimum": -400,
			"maximum": 1500,
			"value": 72,
			"readonly": true
		},
		"wind_peak": {
			"type": "numeric",
			"minimum": 0,
			"maximum": 100000,
			"value": 2501,
			"readonly": true
		}
	}
}`

**Comment by muhlba91** [comment] 2023-11-15 11:46
thank you for your feedbacks and the API output! 👍 

i‘ll go ahead and map the onyx sensor values to HA sensors to add basic support for the weather station.

**Comment by mrogin-technic** [comment] 2023-11-15 11:49
Thank you very much.

**Comment by muhlba91** [comment] 2023-11-16 10:22
can you please test `v7.0.0-beta.0`?

i have added the HA sensors for the weather sensor values. as i don't have any testing possibility, please confirm if it's working or let me know of any bugs you find.

**Comment by mrogin-technic** [comment] 2023-11-16 10:38
I will test it tonight. As I have just started with Home Assistant, my question is how to test a new beta release?
Grüße aus Innsbruck

**Comment by muhlba91** [comment] 2023-11-16 10:45
if you have [HACS](https://hacs.xyz) installed in your HA, you can search for this integration (as you do with a non-beta release) if you add the repository. then you can enable beta versions in HACS: https://hacs.xyz/docs/faq/beta/.

alternatively, you can just check out the git tag and overwrite the (already existing) custom component in the `custom_components/hella_onyx` directory of your HA installation with the contents of this repository's directory [`custom_components/heally_onyx`](https://github.com/muhlba91/onyx-homeassistant-integration/tree/v7.0.0-beta.0/custom_components/hella_onyx).

don't forget to restart HA afterwards to load the new integration version and install dependencies.

**Comment by mrogin-technic** [comment] 2023-11-16 10:51
Thank you very much. I will try it and give feedback tomorrow.

**Comment by Jibberchris** [comment] 2023-11-16 13:42
I have just updated to v7.0.0-beta.0 and have now received the weather station as a new device and 7 new entities in HA. The values of all sensors match those from the Onyx app. The only difference is the wind speed. This is displayed in the app in m/s and in Homeassistant in km/h (but correctly converted). Perfect. So far I have not been able to detect any errors. Thank you so much.
![screen](https://github.com/muhlba91/onyx-homeassistant-integration/assets/121609026/7c599a52-06af-4aa9-bb06-7aecf68c795d)

**Comment by mrogin-technic** [comment] 2023-11-16 14:29
Great, I'm looking forward to my test.
I think the 3 decimal places for the wind peak are too many, one decimal place should be sufficient and would fit better with the temperature value with one decimal place.

**Comment by muhlba91** [comment] 2023-11-16 15:32
thanks for the feedback! 👍 

regarding the wind peak, i am setting m/s as the unit (https://github.com/muhlba91/onyx-homeassistant-integration/blob/main/custom_components/hella_onyx/sensors/weather.py#L147), but HA will convert it to the preferred user unit. so i guess there's km/h set as your default somewhere.

regarding the decimal places, i can add a suggested precision and set it to 1 decimal place, and users can set the precision differently in the UI by clicking on the gear icon on the entity. my idea is the following suggested precisions:
- humidity: 0
- wind, temperature, brightness: 1

does this default suggestion of the decimal precision make sense for the implementation of these sensors?

btw, you can manually set the unit and decimal places for each entity: click on the entity and the settings button (gear icon) in the opened dialog.

**Comment by muhlba91** [comment] 2023-11-16 16:28
i have now set the suggested precisions with brightness to 0 decimal places.

can you please try `v7.0.0-beta.1` to test if this configuration is considered?

as for `lx` vs `klx`, HA only supports `lx` as the unit for brightness; hence, i can not manipulate this one.

**Comment by muhlba91** [comment] 2023-11-16 19:16
i'm sorry - this was an unrelated change which was not supposed to get into main yet. i reverted that change with `v7.0.0-beta.2` - can you please try and confirm?

**Comment by mrogin-technic** [comment] 2023-11-16 19:42
v7.0.0-beta.2 works, many thanks.

![image](https://github.com/muhlba91/onyx-homeassistant-integration/assets/20296380/55947007-249d-4bc6-8ba9-d8839b649988)

**Comment by muhlba91** [comment] 2023-11-16 20:01
awesome, thank you a lot for trying it and providing feedback. 👍🏻

i‘ll draft the final release tomorrow unless there are any errors coming up from the beta.

**Comment by mrogin-technic** [comment] 2023-11-16 23:37
Is it possible to sort the order of the weather measured values?
e.g.:
Temperature
Humidity
Wind Peak
Air Pressure
Sun Brightness Peak
Sun Brightness Sink
Device Type

Otherwise, everything worked as expected so far and the charts also looks good.
![image](https://github.com/muhlba91/onyx-homeassistant-integration/assets/20296380/4a87ae44-bc69-4ac9-ac4f-c436b1ee2030)

**Comment by muhlba91** [comment] 2023-11-17 07:37
cool, thanks for the feedback - i'll draft a release during the day! 👍 

as for ordering, this is donme by HA itself. by default it's ordered by name alphabetically. you can rename each sensor btw, and also create your own dashboard with a certain ordering but that's nothing an integration can influence.

**Comment by muhlba91** [comment] 2023-11-17 08:50
`v7.0.0` is released; closing this issue.

**Closed by muhlba91** 2023-11-17 08:50 UTC
Labels: enhancement

**Comment by mrogin-technic** [comment] 2023-11-20 15:41
@Jibberchris  Are the measured brightness values from your weather station also 10 times higher than the real expected values?
The maximum possible sun brightness is 130,000 lx with a clear sky and the sun at its zenith. In central Europe, a maximum of 90,000 lx should be reached at midday in summer and a maximum of 20,000 lx at midday in winter. This morning at 9:14 a.m., for example, my weather sensor measured hit the upper limit of the sensor at 150,000 lx. However, a maximum of 15,000 lx would be expected at this time.
![2023-11-20_15-56-56](https://github.com/muhlba91/onyx-homeassistant-integration/assets/20296380/cf4ea076-585b-433f-bf6b-5566e0f5940a)

**Comment by Jibberchris** [comment] 2023-11-21 13:50
no, my values tend to be too low, but that's because my weather station is currently mounted under a canopy and is therefore in the shade - even so, I usually only have values of around 500lx on the last few foggy days, so I feel that the values are 10 times too low. In any case, the values in the app are the same as the values in the Home Assistant. Maybe we should write to Hella support.

**Comment by mrogin-technic** [comment] 2023-11-21 13:55
> no, my values tend to be too low, but that's because my weather station is currently mounted under a canopy and is therefore in the shade - even so, I usually only have values of around 500lx on the last few foggy days, so I feel that the values are 10 times too low. In any case, the values in the app are the same as the values in the Home Assistant. Maybe we should write to Hella support.

I spoke to the chief developer at Hella on the phone today and had already sent him my data per mail, which he said should not be correct.

**Comment by muhlba91** [comment] 2023-11-21 15:49
@mrogin-technic just to be sure: the values shown in HA are the same as shown in the ONYX app?

because then that would indeed mean there‘s some measurement error in the device or ONYX itself but not caused by this integration when getting the values.

**Comment by mrogin-technic** [comment] 2023-11-21 18:16
> @mrogin-technic just to be sure: the values shown in HA are the same as shown in the ONYX app?
> 
> because then that would indeed mean there‘s some measurement error in the device or ONYX itself but not caused by this integration when getting the values.

Yes, the values shown in HA are the same as shown in the ONYX app and ONYX itself show unrealistic sun brightness values for my ONYX.WEATHER. That's why I asked @Jibberchris directly, because if it was the same with him in the sun, it would have to be a bug with onyx software.

**Comment by mrogin-technic** [comment] 2023-11-23 16:25
Today, the sun shone all day under a cloudless sky. However, it turned out that the brightness sensors of the ONYX.WEATHER-Station unfortunately do not provide meaningful values.
At 9:15 a.m., 150.000 lux were already measured at low brightness as the sun was only 12.8° height above the horizon. However, at midday, when the sunlight and brightness were at their highest, the measured values fell significantly down to 42.000 lx and rose again in the late afternoon and 100.000 lux were measured at sunset.

![2023-11-23_17-23-03](https://github.com/muhlba91/onyx-homeassistant-integration/assets/20296380/d3700684-5ee2-4052-a006-f7d06f45e542)
