### ISSUE TITLE
Error setting up entry ONYX for hella_onyx

### ISSUE THREAD

**Issue by tbarth64** [muhlba91/onyx-homeassistant-integration#8] opened 2021-11-11 14:29 UTC
**Describe the bug.**
Logger: homeassistant.config_entries
Source: custom_components/hella_onyx/api_connector.py:36
Integration: Hella ONYX.CENTER (documentation, issues)

**To Reproduce.**
Every time the integration starts

**Expected behavior.**
na

**Environment (please complete the following information):**
 - HA docker image 2021.11.2  (same on 2021.10.4)  
 - onyx version 1.2.0

**Additional context.**
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 304, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/hella_onyx/__init__.py", line 67, in async_setup_entry
    await onyx_api.update()
  File "/config/custom_components/hella_onyx/api_connector.py", line 36, in update
    devices = await client.devices(include_details=True)
  File "/usr/local/lib/python3.9/site-packages/onyx_client/client.py", line 240, in devices
    for device in [await self.device(key) for key, _ in data.items()]
  File "/usr/local/lib/python3.9/site-packages/onyx_client/client.py", line 240, in <listcomp>
    for device in [await self.device(key) for key, _ in data.items()]
  File "/usr/local/lib/python3.9/site-packages/onyx_client/client.py", line 269, in device
    data["properties"],
KeyError: 'properties'

**Comment by muhlba91** [comment] 2021-11-21 13:35
Hi,

thanks for submitting this bug. Did you recently update the ONYX.CENTER?

The integration uses the v2 API and with the recent update, API v3 was released with no support for v2 anymore (due to stability issues). Some properties have been removed by the new API version which the integration relies on.

**Comment by tbarth64** [comment] 2021-11-21 14:53
Hi,

thanks for the update.
Yes, as I can remember, there was an update some weeks ago.
But I didn’t recognize the chance of API version. 
Did you plan to support v3 API in the future?

Best Regards 
Thomas

**Comment by muhlba91** [comment] 2021-11-21 14:59
To verify you can follow https://github.com/hella-info/onyx_api#examples-1 to get the list of supported API versions. If v3 is listed, this is very likely to be the root cause.

Yes, I plan on updating it to use API v3 (#9) and am working on it. I cannot estimate an ETA yet since quite a bit changed in the API this integration relied on (drive and rotation time, switched drive direction), and I need to refactor and test the logic using the new API. I also believe there might be some changes coming up in how the covers in HA behave.

**Comment by tbarth64** [comment] 2021-11-21 15:40
I checked it and your right, all three versions are listed.

Thank you for your help and good luck to get it work ;)

Have a nice weekend 

Regards,
Thomas

**Comment by muhlba91** [comment] 2021-11-22 11:03
I have released a beta version including v3 support (`v2.0.0-beta.0`). I ran various tests so far and didn't find issues, and actually think it got more stable. Feel free to test and provide an update; I plan to promote it to stable by end of the week or beginning next week if no major bugs occur.

Additionally, I have added a device filter to remove lights and weather stations. I do not have such devices for testing available, and they were also able to break the integration previously.

**Comment by tbarth64** [comment] 2021-11-22 13:02
Thanks, I upgraded to the 2.0.0_beta, but then I got this error, after restart of HA:

# grep -i vers manifest.json  
 "version": "2.0.0-beta.0"

Logger: homeassistant.config_entries
Source: custom_components/hella_onyx/api_connector.py:45
Integration: Hella ONYX.CENTER (documentation, issues)
First occurred: 13:23:15 (1 occurrences)
Last logged: 13:23:15

Error setting up entry ONYX for hella_onyx
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 304, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/hella_onyx/__init__.py", line 77, in async_setup_entry
    await onyx_api.update()
  File "/config/custom_components/hella_onyx/api_connector.py", line 45, in update
    devices = await client.devices(include_details=True)
  File "/usr/local/lib/python3.9/site-packages/onyx_client/client.py", line 247, in devices
    for device in [await self.device(key) for key, _ in data.items()]
  File "/usr/local/lib/python3.9/site-packages/onyx_client/client.py", line 247, in <listcomp>
    for device in [await self.device(key) for key, _ in data.items()]
  File "/usr/local/lib/python3.9/site-packages/onyx_client/client.py", line 276, in device
    data["properties"],
KeyError: 'properties'


If you need further information,logs,... let me know.

Thanks in advance
Thomas

**Comment by muhlba91** [comment] 2021-11-22 13:18
thanks for this update. the bug/problem lies in retrieving the device's data via the `/devices/<id>` API where the `properties` key is missing.

could you let me know what devices you have in your ONYX.CENTER - anything else than raffstores/shutters?

according to https://github.com/hella-info/onyx_api#device-properties-and-actions-1 every entity should have properties. i probably can "work around" this but would like to know the root cause/device.
if you don't have a lot of devices registered, would you mind doing the following:
- call `/devices` and note down the identifiers (https://github.com/hella-info/onyx_api#list-all-devices)
- for each identifier call the `/devices/<id>` API (https://github.com/hella-info/onyx_api#device-details)
- do you find any device without a `properties` field? if so, could you post the response of this call (remove any "private" information)

**Comment by tbarth64** [comment] 2021-11-22 13:41
I have three devices:
server:~ # curl -s -H "Authorization: Bearer <TOKEN>" https://api.hella.link/box/<FP>/api/v3/devices |json_pp
{
   "f4794f82-6937-4602-b0bb-d53f69165399" : {
      "name" : "Windwächter",
      "type" : "weather"
   },
   "726802cb-feda-41b6-8803-47e3345238de" : {
      "offline" : true,
      "name" : "Handsender",
      "type" : "click"
   },
   "2821d09f-34d8-4ff1-92fb-9e7ceb2b4250" : {
      "type" : "awning",
      "name" : "Markise"
   }
}

Markise and Windwächter do have properties, but not the Handsender:

server:~ # curl -s -H "Authorization: Bearer <TOKEN>" https://api.hella.link/box/<FP>/api/v3/devices/726802cb-feda-41b6-8803-47e3345238de |json_pp
{
   "name" : "Handsender",
   "type" : "click",
   "offline" : true
}


Is there a possibility to filter out such devices?

Thanks
Thomas

**Comment by muhlba91** [comment] 2021-11-22 14:04
awesome, this helps a lot (and makes sense now)! the `click` type is not mentioned in their documentation.

fyi, i have cross-created an issue in the client this integration uses: https://github.com/muhlba91/onyx-client/issues/8
this will contain adding support/mapping for this device and not relying on an existing `properties` field. once done, i'll release a new beta for this integration. since it will only filter by shutters (which are supported currently), the click device will then be filtered.

**Comment by muhlba91** [comment] 2021-11-22 15:18
@tbarth64 could you please test with `v2.0.0-beta.1`?

i have updated the client to treat click devices and others without a `properties` field correctly. (this is the test case for the payload from the click device: https://github.com/muhlba91/onyx-client/blob/main/tests/test_client.py#L541)

**Comment by tbarth64** [comment] 2021-11-22 15:20
Great, the v2.0.0-beta.1 does function.
I can move the cover, but the position is the wrong way round  ... 0 -> completely out, 100 -> in.
Is this from the new API?

And I do get this error:
Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: custom_components.hella_onyx.event_thread
Source: custom_components/hella_onyx/event_thread.py:43
Integration: Hella ONYX.CENTER (documentation, issues)
First occurred: 16:10:00 (3 occurrences)
Last logged: 16:14:59

connection reset: 'NoneType' object has no attribute 'get', restarting: True (backoff = 91 seconds)
connection reset: 'NoneType' object has no attribute 'get', restarting: True (backoff = 207 seconds)
connection reset: 'NoneType' object has no attribute 'get', restarting: True (backoff = 535 seconds)

Regards,
Thomas

**Comment by muhlba91** [comment] 2021-11-22 17:12
yes, this could very well be. in v2 they provided a `switch_drive_direction` which was used to invert the values.
this is not present anymore, and i need to assume a direction with which the values correspond with how HA expects them (0 is closed, 100 is fully open) -> https://github.com/muhlba91/onyx-homeassistant-integration/blob/next/custom_components/hella_onyx/cover.py#L112.
funnily enough, for all my shutters and raffstores (non-switched direction) i actually need to invert the position to have HA show the correct behaviour and translate the values to the correct position as expected by the API.
if your cover is behaving differently - has inverted values - to this assumption, it will be the wrong way round until we receive the `switch_drive_direction` through the API again. (if we do, i need to "revert" my changes to get the "old logic" back.)

ok, this click device is interesting. i'll have another try at `v2.0.0-beta.2`. (thanks for your help and patience! 😃)

**Comment by muhlba91** [comment] 2021-11-23 11:40
@tbarth64 please also check https://github.com/hella-info/onyx_api/issues/6#issuecomment-976366851.
the open/closed values are now consistently exposed through the API for all devices. 0 is fully retracted / 100 is fully opened.
unfortunately, HA expects it the other way round ->  the `open_cover` arrow/method is only possible to execute if the position is 0.

this leads to unexpected behaviour. i have now 2 options:
1. be inconsistent with HA and reverse everything -> like `open` will be `close` and HA's arrows will kinda do exactly the opposite; this is consistent to Hella
2. be inconsistent with Hella -> like invert 0 and 100 for HA to work consistently with the cover entity; this is inconsistent to HA

to me, 2) is the highly favoured way to go. people expect the cover entity to work this way, and this plays a role in automations as well. i strongly believe an integration should adhere to the correct commands as mapped out by HA in this case. if every integration re-imagines the states, automations will break easily.
if there are strong arguments against sticking to 2), let me know.

**Comment by tbarth64** [comment] 2021-11-23 12:10
v2.0.0-beta.2 solves the last issue, you are a hero!
And yes I go with you, be consistent inside HA might be the better way. 
Maybe Hella will change the behavior somehow in the future ... ;-)

**Closed** 2021-11-24 14:45 UTC
Labels: bug
